pipeline {
  agent any
  stages {
    stage('克隆项目') {
      steps {
        sh 'git clone https://${CODING_KEY}@e.coding.net/jxsfgz-cat/github-release-download/github-release-download.git .'
        }
      }
      stage('下载release') {
        steps {
          sh 'wget --no-check-certificate --content-disposition https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0-beta.3/PicGo-Setup-2.3.0-beta.3.exe'
          sh 'ls -a'
        }
      }
      stage('上传至download分支') {
        steps {
          sh 'git checkout -b download'
          sh 'git add -A && git commit -m "update-release"'
          sh 'git push --set-upstream origin download'
        }
      }
      stage('下载完毕，请前往download下载，完成后请删除download分支') {
        steps {
          echo '下载完毕，请前往download下载，完成后请删除download分支'
        }
      }
    }
  }
